#############################################################################
# Makefile for building: pong-client
# Generated by qmake (3.0) (Qt 5.0.2) on: lun. avr. 15 17:49:59 2013
# Project:  pong-client.pro
# Template: app
# Command: /usr/lib/qt/bin/qmake -spec linux-g++-64 QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o Makefile pong-client.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /usr/bin/gcc
CXX           = /usr/bin/g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -g3 -gdwarf-2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -g3 -gdwarf-2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/qt/mkspecs/linux-g++-64 -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		renderlabel.cpp \
		scene.cpp \
		bat.cpp \
		jobcannotbedone.cpp \
		arena.cpp \
		mathutils.cpp \
		serveurcommunicator.cpp \
		clientcommunicator.cpp \
		GameState.cpp \
		Lockable.cpp \
		serversync.cpp moc_mainwindow.cpp \
		moc_renderlabel.cpp \
		moc_scene.cpp \
		moc_serveurcommunicator.cpp \
		moc_clientcommunicator.cpp \
		moc_serversync.cpp
OBJECTS       = main.o \
		mainwindow.o \
		renderlabel.o \
		scene.o \
		bat.o \
		jobcannotbedone.o \
		arena.o \
		mathutils.o \
		serveurcommunicator.o \
		clientcommunicator.o \
		GameState.o \
		Lockable.o \
		serversync.o \
		moc_mainwindow.o \
		moc_renderlabel.o \
		moc_scene.o \
		moc_serveurcommunicator.o \
		moc_clientcommunicator.o \
		moc_serversync.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/shell-unix.conf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_v8.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/unix/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/wayland-scanner.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		pong-client.pro \
		pong-client.pro
QMAKE_TARGET  = pong-client
DESTDIR       = 
TARGET        = pong-client


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pong-client.pro /usr/lib/qt/mkspecs/linux-g++-64/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/shell-unix.conf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_v8.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/unix/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/wayland-scanner.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		pong-client.pro \
		/lib/libQt5Widgets.prl \
		/lib/libQt5Network.prl \
		/lib/libQt5Gui.prl \
		/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o Makefile pong-client.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/shell-unix.conf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_clucene.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_v8.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/unix/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/wayland-scanner.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
pong-client.pro:
/lib/libQt5Widgets.prl:
/lib/libQt5Network.prl:
/lib/libQt5Gui.prl:
/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o Makefile pong-client.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/pong-client1.0.0 || mkdir -p .tmp/pong-client1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/pong-client1.0.0/ && $(COPY_FILE) --parents mainwindow.h renderlabel.h scene.h bat.h jobcannotbedone.h arena.h mathutils.h serveurcommunicator.h clientcommunicator.h GameState.hpp PongTypes.hpp Lockable.hpp serversync.h .tmp/pong-client1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp renderlabel.cpp scene.cpp bat.cpp jobcannotbedone.cpp arena.cpp mathutils.cpp serveurcommunicator.cpp clientcommunicator.cpp GameState.cpp Lockable.cpp serversync.cpp .tmp/pong-client1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/pong-client1.0.0/ && (cd `dirname .tmp/pong-client1.0.0` && $(TAR) pong-client1.0.0.tar pong-client1.0.0 && $(COMPRESS) pong-client1.0.0.tar) && $(MOVE) `dirname .tmp/pong-client1.0.0`/pong-client1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/pong-client1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_renderlabel.cpp moc_scene.cpp moc_serveurcommunicator.cpp moc_clientcommunicator.cpp moc_serversync.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_renderlabel.cpp moc_scene.cpp moc_serveurcommunicator.cpp moc_clientcommunicator.cpp moc_serversync.cpp
moc_mainwindow.cpp: /usr/include/qt/QtWidgets/QMainWindow \
		/usr/include/qt/QtWidgets/qmainwindow.h \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtWidgets/qtabwidget.h \
		/usr/include/qt/QtGui/qicon.h \
		mainwindow.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_renderlabel.cpp: scene.h \
		/usr/include/qt/QtWidgets/QWidget \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtCore/QVector \
		/usr/include/qt/QtCore/QPointF \
		/usr/include/qt/QtGui/QPainter \
		/usr/include/qt/QtGui/qpainter.h \
		/usr/include/qt/QtGui/qtextoption.h \
		/usr/include/qt/QtGui/qpen.h \
		/usr/include/qt/QtCore/QLine \
		/usr/include/qt/QtCore/QString \
		/usr/include/qt/QtWidgets/QErrorMessage \
		/usr/include/qt/QtWidgets/qerrormessage.h \
		/usr/include/qt/QtWidgets/qdialog.h \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		/usr/include/qt/QtCore/QThread \
		/usr/include/qt/QtCore/qthread.h \
		bat.h \
		/usr/include/qt/QtCore/QDataStream \
		arena.h \
		/usr/include/qt/QtGui/QPen \
		jobcannotbedone.h \
		serversync.h \
		/usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtNetwork/QHostAddress \
		/usr/include/qt/QtNetwork/qhostaddress.h \
		/usr/include/qt/QtNetwork/qabstractsocket.h \
		/usr/include/qt/QtNetwork/QTcpSocket \
		/usr/include/qt/QtNetwork/qtcpsocket.h \
		PongTypes.hpp \
		/usr/include/qt/QtWidgets/QLabel \
		/usr/include/qt/QtWidgets/qlabel.h \
		/usr/include/qt/QtWidgets/qframe.h \
		/usr/include/qt/QtGui/QKeyEvent \
		/usr/include/qt/QtGui/QMouseEvent \
		renderlabel.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) renderlabel.h -o moc_renderlabel.cpp

moc_scene.cpp: /usr/include/qt/QtWidgets/QWidget \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtCore/QVector \
		/usr/include/qt/QtCore/QPointF \
		/usr/include/qt/QtGui/QPainter \
		/usr/include/qt/QtGui/qpainter.h \
		/usr/include/qt/QtGui/qtextoption.h \
		/usr/include/qt/QtGui/qpen.h \
		/usr/include/qt/QtCore/QLine \
		/usr/include/qt/QtCore/QString \
		/usr/include/qt/QtWidgets/QErrorMessage \
		/usr/include/qt/QtWidgets/qerrormessage.h \
		/usr/include/qt/QtWidgets/qdialog.h \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		/usr/include/qt/QtCore/QThread \
		/usr/include/qt/QtCore/qthread.h \
		bat.h \
		/usr/include/qt/QtCore/QDataStream \
		arena.h \
		/usr/include/qt/QtGui/QPen \
		jobcannotbedone.h \
		serversync.h \
		/usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtNetwork/QHostAddress \
		/usr/include/qt/QtNetwork/qhostaddress.h \
		/usr/include/qt/QtNetwork/qabstractsocket.h \
		/usr/include/qt/QtNetwork/QTcpSocket \
		/usr/include/qt/QtNetwork/qtcpsocket.h \
		PongTypes.hpp \
		scene.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) scene.h -o moc_scene.cpp

moc_serveurcommunicator.cpp: /usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/QVector \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtCore/QLineF \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtCore/QDataStream \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		GameState.hpp \
		PongTypes.hpp \
		Lockable.hpp \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		bat.h \
		/usr/include/qt/QtCore/QPointF \
		serveurcommunicator.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) serveurcommunicator.h -o moc_serveurcommunicator.cpp

moc_clientcommunicator.cpp: /usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/QDataStream \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		clientcommunicator.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) clientcommunicator.h -o moc_clientcommunicator.cpp

moc_serversync.cpp: /usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/QPointF \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtWidgets/QErrorMessage \
		/usr/include/qt/QtWidgets/qerrormessage.h \
		/usr/include/qt/QtWidgets/qdialog.h \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtCore/QString \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		/usr/include/qt/QtCore/QDataStream \
		/usr/include/qt/QtNetwork/QHostAddress \
		/usr/include/qt/QtNetwork/qhostaddress.h \
		/usr/include/qt/QtNetwork/qabstractsocket.h \
		/usr/include/qt/QtNetwork/QTcpSocket \
		/usr/include/qt/QtNetwork/qtcpsocket.h \
		bat.h \
		/usr/include/qt/QtCore/QVector \
		PongTypes.hpp \
		serversync.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) serversync.h -o moc_serversync.cpp

compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		renderlabel.h \
		scene.h \
		/usr/include/qt/QtWidgets/QWidget \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtCore/QVector \
		/usr/include/qt/QtCore/QPointF \
		/usr/include/qt/QtGui/QPainter \
		/usr/include/qt/QtGui/qpainter.h \
		/usr/include/qt/QtGui/qtextoption.h \
		/usr/include/qt/QtGui/qpen.h \
		/usr/include/qt/QtCore/QLine \
		/usr/include/qt/QtCore/QString \
		/usr/include/qt/QtWidgets/QErrorMessage \
		/usr/include/qt/QtWidgets/qerrormessage.h \
		/usr/include/qt/QtWidgets/qdialog.h \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		/usr/include/qt/QtCore/QThread \
		/usr/include/qt/QtCore/qthread.h \
		bat.h \
		/usr/include/qt/QtCore/QDataStream \
		arena.h \
		/usr/include/qt/QtGui/QPen \
		jobcannotbedone.h \
		serversync.h \
		/usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtNetwork/QHostAddress \
		/usr/include/qt/QtNetwork/qhostaddress.h \
		/usr/include/qt/QtNetwork/qabstractsocket.h \
		/usr/include/qt/QtNetwork/QTcpSocket \
		/usr/include/qt/QtNetwork/qtcpsocket.h \
		PongTypes.hpp \
		/usr/include/qt/QtWidgets/QLabel \
		/usr/include/qt/QtWidgets/qlabel.h \
		/usr/include/qt/QtWidgets/qframe.h \
		/usr/include/qt/QtGui/QKeyEvent \
		/usr/include/qt/QtGui/QMouseEvent
	/usr/lib/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/include/qt/QtWidgets/QMainWindow \
		/usr/include/qt/QtWidgets/qmainwindow.h \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtWidgets/qtabwidget.h \
		/usr/include/qt/QtGui/qicon.h \
		/usr/include/qt/QtWidgets/QApplication \
		/usr/include/qt/QtWidgets/qapplication.h \
		/usr/include/qt/QtCore/qcoreapplication.h \
		/usr/include/qt/QtCore/qeventloop.h \
		/usr/include/qt/QtWidgets/qdesktopwidget.h \
		/usr/include/qt/QtGui/qguiapplication.h \
		/usr/include/qt/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/include/qt/QtWidgets/QMainWindow \
		/usr/include/qt/QtWidgets/qmainwindow.h \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtWidgets/qtabwidget.h \
		/usr/include/qt/QtGui/qicon.h \
		ui_mainwindow.h \
		/usr/include/qt/QtCore/QVariant \
		/usr/include/qt/QtWidgets/QAction \
		/usr/include/qt/QtWidgets/qaction.h \
		/usr/include/qt/QtWidgets/qactiongroup.h \
		/usr/include/qt/QtWidgets/QApplication \
		/usr/include/qt/QtWidgets/qapplication.h \
		/usr/include/qt/QtCore/qcoreapplication.h \
		/usr/include/qt/QtCore/qeventloop.h \
		/usr/include/qt/QtWidgets/qdesktopwidget.h \
		/usr/include/qt/QtGui/qguiapplication.h \
		/usr/include/qt/QtGui/qinputmethod.h \
		/usr/include/qt/QtWidgets/QButtonGroup \
		/usr/include/qt/QtWidgets/qbuttongroup.h \
		/usr/include/qt/QtWidgets/QHeaderView \
		/usr/include/qt/QtWidgets/qheaderview.h \
		/usr/include/qt/QtWidgets/qabstractitemview.h \
		/usr/include/qt/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt/QtWidgets/qframe.h \
		/usr/include/qt/QtCore/qabstractitemmodel.h \
		/usr/include/qt/QtCore/qitemselectionmodel.h \
		/usr/include/qt/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt/QtWidgets/qstyleoption.h \
		/usr/include/qt/QtWidgets/qabstractspinbox.h \
		/usr/include/qt/QtGui/qvalidator.h \
		/usr/include/qt/QtWidgets/qslider.h \
		/usr/include/qt/QtWidgets/qabstractslider.h \
		/usr/include/qt/QtWidgets/qstyle.h \
		/usr/include/qt/QtWidgets/qtabbar.h \
		/usr/include/qt/QtWidgets/qrubberband.h \
		/usr/include/qt/QtWidgets/QWidget \
		renderlabel.h \
		scene.h \
		/usr/include/qt/QtCore/QVector \
		/usr/include/qt/QtCore/QPointF \
		/usr/include/qt/QtGui/QPainter \
		/usr/include/qt/QtGui/qpainter.h \
		/usr/include/qt/QtGui/qtextoption.h \
		/usr/include/qt/QtGui/qpen.h \
		/usr/include/qt/QtCore/QLine \
		/usr/include/qt/QtCore/QString \
		/usr/include/qt/QtWidgets/QErrorMessage \
		/usr/include/qt/QtWidgets/qerrormessage.h \
		/usr/include/qt/QtWidgets/qdialog.h \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		/usr/include/qt/QtCore/QThread \
		/usr/include/qt/QtCore/qthread.h \
		bat.h \
		/usr/include/qt/QtCore/QDataStream \
		arena.h \
		/usr/include/qt/QtGui/QPen \
		jobcannotbedone.h \
		serversync.h \
		/usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtNetwork/QHostAddress \
		/usr/include/qt/QtNetwork/qhostaddress.h \
		/usr/include/qt/QtNetwork/qabstractsocket.h \
		/usr/include/qt/QtNetwork/QTcpSocket \
		/usr/include/qt/QtNetwork/qtcpsocket.h \
		PongTypes.hpp \
		/usr/include/qt/QtWidgets/QLabel \
		/usr/include/qt/QtWidgets/qlabel.h \
		/usr/include/qt/QtGui/QKeyEvent \
		/usr/include/qt/QtGui/QMouseEvent \
		/usr/include/qt/QtCore/QTimer \
		/usr/include/qt/QtCore/qtimer.h \
		/usr/include/qt/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

renderlabel.o: renderlabel.cpp renderlabel.h \
		scene.h \
		/usr/include/qt/QtWidgets/QWidget \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtCore/QVector \
		/usr/include/qt/QtCore/QPointF \
		/usr/include/qt/QtGui/QPainter \
		/usr/include/qt/QtGui/qpainter.h \
		/usr/include/qt/QtGui/qtextoption.h \
		/usr/include/qt/QtGui/qpen.h \
		/usr/include/qt/QtCore/QLine \
		/usr/include/qt/QtCore/QString \
		/usr/include/qt/QtWidgets/QErrorMessage \
		/usr/include/qt/QtWidgets/qerrormessage.h \
		/usr/include/qt/QtWidgets/qdialog.h \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		/usr/include/qt/QtCore/QThread \
		/usr/include/qt/QtCore/qthread.h \
		bat.h \
		/usr/include/qt/QtCore/QDataStream \
		arena.h \
		/usr/include/qt/QtGui/QPen \
		jobcannotbedone.h \
		serversync.h \
		/usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtNetwork/QHostAddress \
		/usr/include/qt/QtNetwork/qhostaddress.h \
		/usr/include/qt/QtNetwork/qabstractsocket.h \
		/usr/include/qt/QtNetwork/QTcpSocket \
		/usr/include/qt/QtNetwork/qtcpsocket.h \
		PongTypes.hpp \
		/usr/include/qt/QtWidgets/QLabel \
		/usr/include/qt/QtWidgets/qlabel.h \
		/usr/include/qt/QtWidgets/qframe.h \
		/usr/include/qt/QtGui/QKeyEvent \
		/usr/include/qt/QtGui/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderlabel.o renderlabel.cpp

scene.o: scene.cpp scene.h \
		/usr/include/qt/QtWidgets/QWidget \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtCore/QVector \
		/usr/include/qt/QtCore/QPointF \
		/usr/include/qt/QtGui/QPainter \
		/usr/include/qt/QtGui/qpainter.h \
		/usr/include/qt/QtGui/qtextoption.h \
		/usr/include/qt/QtGui/qpen.h \
		/usr/include/qt/QtCore/QLine \
		/usr/include/qt/QtCore/QString \
		/usr/include/qt/QtWidgets/QErrorMessage \
		/usr/include/qt/QtWidgets/qerrormessage.h \
		/usr/include/qt/QtWidgets/qdialog.h \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		/usr/include/qt/QtCore/QThread \
		/usr/include/qt/QtCore/qthread.h \
		bat.h \
		/usr/include/qt/QtCore/QDataStream \
		arena.h \
		/usr/include/qt/QtGui/QPen \
		jobcannotbedone.h \
		serversync.h \
		/usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtNetwork/QHostAddress \
		/usr/include/qt/QtNetwork/qhostaddress.h \
		/usr/include/qt/QtNetwork/qabstractsocket.h \
		/usr/include/qt/QtNetwork/QTcpSocket \
		/usr/include/qt/QtNetwork/qtcpsocket.h \
		PongTypes.hpp \
		/usr/include/qt/QtGui/QBrush \
		/usr/include/qt/QtGui/QColor
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scene.o scene.cpp

bat.o: bat.cpp bat.h \
		/usr/include/qt/QtCore/QPointF \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/QVector \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/QDataStream \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bat.o bat.cpp

jobcannotbedone.o: jobcannotbedone.cpp jobcannotbedone.h \
		/usr/include/qt/QtCore/QString \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jobcannotbedone.o jobcannotbedone.cpp

arena.o: arena.cpp arena.h \
		/usr/include/qt/QtGui/QPainter \
		/usr/include/qt/QtGui/qpainter.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qtextoption.h \
		/usr/include/qt/QtGui/qpen.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/QPen \
		/usr/include/qt/QtCore/QVector \
		/usr/include/qt/QtCore/QLine \
		bat.h \
		/usr/include/qt/QtCore/QPointF \
		/usr/include/qt/QtCore/QDataStream \
		mathutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arena.o arena.cpp

mathutils.o: mathutils.cpp mathutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mathutils.o mathutils.cpp

serveurcommunicator.o: serveurcommunicator.cpp serveurcommunicator.h \
		/usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/QVector \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtCore/QLineF \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtCore/QDataStream \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		GameState.hpp \
		PongTypes.hpp \
		Lockable.hpp \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		bat.h \
		/usr/include/qt/QtCore/QPointF
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serveurcommunicator.o serveurcommunicator.cpp

clientcommunicator.o: clientcommunicator.cpp clientcommunicator.h \
		/usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/QDataStream \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientcommunicator.o clientcommunicator.cpp

GameState.o: GameState.cpp GameState.hpp \
		PongTypes.hpp \
		Lockable.hpp \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameState.o GameState.cpp

Lockable.o: Lockable.cpp Lockable.hpp \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Lockable.o Lockable.cpp

serversync.o: serversync.cpp serversync.h \
		/usr/include/qt/QtCore/QObject \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/QPointF \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtWidgets/QErrorMessage \
		/usr/include/qt/QtWidgets/qerrormessage.h \
		/usr/include/qt/QtWidgets/qdialog.h \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtCore/QString \
		/usr/include/qt/QtCore/QMutex \
		/usr/include/qt/QtCore/qmutex.h \
		/usr/include/qt/QtCore/QDataStream \
		/usr/include/qt/QtNetwork/QHostAddress \
		/usr/include/qt/QtNetwork/qhostaddress.h \
		/usr/include/qt/QtNetwork/qabstractsocket.h \
		/usr/include/qt/QtNetwork/QTcpSocket \
		/usr/include/qt/QtNetwork/qtcpsocket.h \
		bat.h \
		/usr/include/qt/QtCore/QVector \
		PongTypes.hpp \
		/usr/include/qt/QtWidgets/QApplication \
		/usr/include/qt/QtWidgets/qapplication.h \
		/usr/include/qt/QtCore/qcoreapplication.h \
		/usr/include/qt/QtCore/qeventloop.h \
		/usr/include/qt/QtWidgets/qdesktopwidget.h \
		/usr/include/qt/QtGui/qguiapplication.h \
		/usr/include/qt/QtGui/qinputmethod.h \
		serveurcommunicator.h \
		/usr/include/qt/QtCore/QLineF \
		GameState.hpp \
		Lockable.hpp \
		clientcommunicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serversync.o serversync.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_renderlabel.o: moc_renderlabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_renderlabel.o moc_renderlabel.cpp

moc_scene.o: moc_scene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scene.o moc_scene.cpp

moc_serveurcommunicator.o: moc_serveurcommunicator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serveurcommunicator.o moc_serveurcommunicator.cpp

moc_clientcommunicator.o: moc_clientcommunicator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientcommunicator.o moc_clientcommunicator.cpp

moc_serversync.o: moc_serversync.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serversync.o moc_serversync.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

